using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.RegularExpressions;
using UnityEditor;
using UnityEditor.Build;
using UnityEditor.Build.Reporting;
using UnityEngine;

namespace Core.Divinity.Editor
{
    /// <summary>Generates compile-time names from the same assets that supply runtime definitions.</summary>
    internal sealed class DeityCodeGenerator : AssetPostprocessor, IPreprocessBuildWithReport
    {
        internal const string OutputPath = "Assets/Core/Divinity/Generated/Deities.g.cs";

        // A capital first letter rules out every C# keyword.
        private static readonly Regex ValidName = new("^[A-Z][A-Za-z0-9_]*$");

        public int callbackOrder => 0;

        [InitializeOnLoadMethod]
        internal static void Schedule()
        {
            EditorApplication.delayCall -= Regenerate;
            EditorApplication.delayCall += Regenerate;
        }

        [MenuItem("Tools/Divine Favour/Regenerate Deities.cs")]
        private static void Regenerate()
        {
            try { Generate(); }
            catch (Exception e) { Debug.LogError($"[Deities] {e.Message}"); }
        }

        private static void OnPostprocessAllAssets(string[] imported, string[] deleted, string[] moved, string[] movedFrom)
        {
            if (imported.Concat(deleted).Concat(moved).Concat(movedFrom).Any(IsDefinitionPath)) Schedule();
        }

        internal static bool IsDefinitionPath(string path) =>
            path.Contains("/Resources/Deities/") && path.EndsWith(".asset", StringComparison.OrdinalIgnoreCase);

        public void OnPreprocessBuild(BuildReport report)
        {
            bool changed;
            try { changed = Generate(); }
            catch (Exception e) { throw new BuildFailedException($"Cannot build with invalid deity names: {e.Message}"); }

            if (changed)
                throw new BuildFailedException("Deity names were regenerated. Let Unity finish compiling, then build again.");
        }

        private static bool Generate()
        {
            var definitions = AssetDatabase.FindAssets("t:DeityDefinition")
                .Select(AssetDatabase.GUIDToAssetPath)
                .Where(IsDefinitionPath)
                .Select(AssetDatabase.LoadAssetAtPath<DeityDefinition>);

            if (!WriteIfChanged(OutputPath, GenerateSource(definitions))) return false;
            AssetDatabase.ImportAsset(OutputPath);
            return true;
        }

        internal static bool WriteIfChanged(string path, string source)
        {
            if (File.Exists(path) && File.ReadAllText(path).Replace("\r\n", "\n") == source) return false;
            Directory.CreateDirectory(Path.GetDirectoryName(path) ?? ".");
            File.WriteAllText(path, source, new UTF8Encoding(false));
            return true;
        }

        internal static string GenerateSource(IEnumerable<DeityDefinition> definitions)
        {
            var members = new SortedDictionary<string, string>(StringComparer.Ordinal);
            foreach (var deity in definitions)
            {
                if (!deity) throw new ArgumentException("A deity definition is missing.");
                var name = GetCodeName(deity);
                if (!ValidName.IsMatch(name) || name == "Deities")
                    throw new ArgumentException($"Deity '{deity.name}' needs a code name starting with a capital letter; '{name}' is invalid or reserved.");
                if (!members.TryAdd(name, deity.Id))
                    throw new ArgumentException($"Duplicate generated deity name '{name}'. Set distinct Code Names on the definitions.");
            }

            var constants = members.Select(m =>
                $"        public const string {m.Key} = \"{m.Value.Replace("\\", "\\\\").Replace("\"", "\\\"")}\";\n");
            return "// <auto-generated />\n// Generated from deity definition assets. Do not edit manually.\n\n" +
                   "namespace Core.Divinity\n{\n    public static class Deities\n    {\n" +
                   string.Concat(constants) + "    }\n}\n";
        }

        // A namespaced ID such as mymod:river_god becomes RiverGod unless CodeName overrides it.
        private static string GetCodeName(DeityDefinition deity)
        {
            if (!string.IsNullOrEmpty(deity.CodeName)) return deity.CodeName;
            var id = deity.Id.Substring(deity.Id.LastIndexOf(':') + 1);
            return string.Concat(Regex.Split(id, "[^A-Za-z0-9]+")
                .Where(w => w.Length > 0)
                .Select(w => char.ToUpperInvariant(w[0]) + w.Substring(1)));
        }
    }
}